cabal-version:      3.0
name:               terminal-go
version:            0.1.0.0
build-type:         Simple

library
    hs-source-dirs: src

    default-extensions:
        TupleSections
        OverloadedLists
        ScopedTypeVariables

    exposed-modules:
        Board
        Parser
        Rules
        Decoder
        Types

    build-depends:
        base >=4.18 && <5,
        array,
        containers,
        transformers

    default-language: Haskell2010

executable Terminal-Go
    main-is: Main.hs
    hs-source-dirs: app

    build-depends:
        base >=4.18 && <5,
        terminal-go

    default-language: Haskell2010

test-suite tests
    type: exitcode-stdio-1.0
    main-is: Test.hs
    hs-source-dirs: test

    build-depends:
        base >=4.18 && <5,
        Terminal-Go,
        HUnit

    default-language: Haskell2010